
slices:
  - sources:
      - model: 01-ai/Yi-1.5-6B-Chat
        layer_range: [0, 32]
      - model: 01-ai/Yi-1.5-6B
        layer_range: [0, 32]    
merge_method: slerp
base_model: 01-ai/Yi-1.5-6B-Chat
parameters:
  t:
    - filter: self_attn
      value: [0, 0.25, 0.5, 0.75, 1]
    - filter: mlp
      value: [1, 0.75, 0.5, 0.25, 0]
    - value: 0.5
dtype: bfloat16
